### ISSUE TITLE
Getting only Replies from tweet creator. 

### ISSUE THREAD

**Issue by smyja** [gmellini/twitter-scraper#2]
If you want a users tweet thread how do you do this. From the read me, it seems this is for only getting new replies to a tweet. I'm asking if a thread reader can be gotten out of this.

**Comment by gmellini** [comment]
The tool dumps the full tweet thread (`twitter-scraper.py`) and monitor new replies (`tweet.monitor.sh`); probably you can have a look to this https://twitter.com/threadreaderapp.

Of course you can find a tweet thread (part of the full thread) inside the scraped content (indented, so you can easly see the replies and follow the various threads)

![image](https://user-images.githubusercontent.com/207359/86506741-a4917780-bdd2-11ea-8c08-fcc36273524a.png)

**Comment by smyja** [comment]
okay. Thanks

**Comment by gmellini** [comment]
closing
