### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Fatima-Haouari** [gmellini/twitter-scraper#4]
Hi,
I am trying to use the replies scraper and I am getting 0 replies for all tweets. Could you please advice?

**Comment by gmellini** [comment]
Really, how do you think I can help you without any information?

**Comment by Fatima-Haouari** [comment]
Hi,
Thanks for quick response. Actually it works perfectly with getting replies that were posted within the past 7 days but for old tweets I am getting 0 replies even if they have. But what I was looking for is getting replies for old tweets? is this supported?

**Comment by gmellini** [comment]
If you read the description on the README
```Twitter search API only returns results from last 7 days. This means that search results are limited to last 7 days```
